import React from 'react';
import { Sparkles, ChevronRight, Lightbulb, Target, BookOpen } from 'lucide-react';

const iconMap = {
  0: Lightbulb,
  1: Target,
  2: BookOpen,
};

const colorMap = [
  {
    border: 'border-indigo-500/20',
    bg: 'bg-indigo-500/8',
    icon: 'text-indigo-400',
    badge: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/20',
    dot: 'bg-indigo-400',
  },
  {
    border: 'border-violet-500/20',
    bg: 'bg-violet-500/8',
    icon: 'text-violet-400',
    badge: 'bg-violet-500/15 text-violet-300 border-violet-500/20',
    dot: 'bg-violet-400',
  },
  {
    border: 'border-cyan-500/20',
    bg: 'bg-cyan-500/8',
    icon: 'text-cyan-400',
    badge: 'bg-cyan-500/15 text-cyan-300 border-cyan-500/20',
    dot: 'bg-cyan-400',
  },
];

const RecommendationCard = ({ recommendations = [] }) => {
  if (!recommendations || recommendations.length === 0) {
    return (
      <div className="bg-slate-900/30 border border-slate-800/80 rounded-3xl p-6 shadow-xs backdrop-blur-md flex flex-col items-center justify-center min-h-[180px]">
        <Sparkles className="h-8 w-8 text-slate-600 mb-3" />
        <p className="text-sm text-slate-500 font-medium">No AI recommendations yet</p>
        <p className="text-xs text-slate-600 mt-1">Recalculate your DNA to get personalized tips</p>
      </div>
    );
  }

  return (
    <div className="bg-slate-900/30 border border-slate-800/80 rounded-3xl p-6 shadow-xs backdrop-blur-md">
      <div className="flex items-center gap-2 mb-5">
        <Sparkles className="h-4.5 w-4.5 text-primary animate-pulse" />
        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">AI-Powered Recommendations</h3>
      </div>

      <div className="space-y-3">
        {recommendations.map((rec, idx) => {
          const Icon = iconMap[idx] || Lightbulb;
          const colors = colorMap[idx % colorMap.length];
          return (
            <div
              key={idx}
              className={`group flex items-start gap-3.5 p-4 rounded-2xl border ${colors.border} ${colors.bg} transition-all duration-200 hover:border-opacity-50`}
            >
              {/* Icon */}
              <div className={`flex-shrink-0 flex items-center justify-center h-8 w-8 rounded-xl bg-slate-900/50 border ${colors.border}`}>
                <Icon className={`h-4 w-4 ${colors.icon}`} />
              </div>

              {/* Content */}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1.5">
                  <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${colors.badge}`}>
                    Tip {idx + 1}
                  </span>
                  <div className={`h-1.5 w-1.5 rounded-full ${colors.dot} animate-pulse`} />
                </div>
                <p className="text-sm text-slate-300 leading-relaxed font-medium">
                  {typeof rec === 'string' ? rec : rec.text || rec.recommendation || JSON.stringify(rec)}
                </p>
              </div>

              <ChevronRight className="h-4 w-4 text-slate-600 group-hover:text-slate-400 transition-colors flex-shrink-0 mt-0.5" />
            </div>
          );
        })}
      </div>

      <p className="text-[10px] text-slate-600 text-center mt-4 font-medium">
        Generated by Gemini AI based on your learning patterns
      </p>
    </div>
  );
};

export default RecommendationCard;
