import { Sparkles, Lightbulb, Target, TrendingUp, AlertCircle, BookOpen } from 'lucide-react';
const ICONS = [Lightbulb, Target, TrendingUp, AlertCircle, BookOpen, Sparkles];
const STYLES = [
  { border: 'border-indigo-500/20', bg: 'bg-indigo-500/6',  icon: 'text-indigo-400',  badge: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/20' },
  { border: 'border-amber-500/20',  bg: 'bg-amber-500/6',   icon: 'text-amber-400',   badge: 'bg-amber-500/15 text-amber-300 border-amber-500/20' },
  { border: 'border-cyan-500/20',   bg: 'bg-cyan-500/6',    icon: 'text-cyan-400',    badge: 'bg-cyan-500/15 text-cyan-300 border-cyan-500/20' },
  { border: 'border-violet-500/20', bg: 'bg-violet-500/6',  icon: 'text-violet-400',  badge: 'bg-violet-500/15 text-violet-300 border-violet-500/20' },
  { border: 'border-rose-500/20',   bg: 'bg-rose-500/6',    icon: 'text-rose-400',    badge: 'bg-rose-500/15 text-rose-300 border-rose-500/20' },
  { border: 'border-emerald-500/20',bg: 'bg-emerald-500/6', icon: 'text-emerald-400', badge: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/20' },
];
const RecommendationPanel = ({ recommendations = [], onRecalculate, loading, generated_at }) => {
  if (!recommendations.length) {
    return (
      <div className="bg-slate-900/40 border border-slate-800/70 rounded-3xl p-6 backdrop-blur-md flex flex-col items-center justify-center min-h-[180px] text-center">
        <Sparkles className="h-8 w-8 text-slate-600 mb-3" />
        <p className="text-sm text-slate-500 font-medium">No recommendations yet</p>
        {onRecalculate && (
          <button onClick={onRecalculate} disabled={loading}
            className="mt-4 px-4 py-2 rounded-xl bg-indigo-500/20 border border-indigo-500/20 text-indigo-300 text-xs font-bold hover:bg-indigo-500/30 transition-all cursor-pointer disabled:opacity-50">
            {loading ? 'Generating...' : '✨ Generate AI Recommendations'}
          </button>
        )}
      </div>
    );
  }
  return (
    <div className="bg-slate-900/40 border border-slate-800/70 rounded-3xl p-6 backdrop-blur-md shadow-xs">
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary animate-pulse" />
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">AI Recommendations</h3>
        </div>
        {generated_at && <span className="text-[9px] text-slate-600 hidden sm:block">{generated_at}</span>}
      </div>
      <div className="space-y-2.5">
        {recommendations.map((rec, idx) => {
          const Icon = ICONS[idx % ICONS.length];
          const style = STYLES[idx % STYLES.length];
          return (
            <div key={idx} className={`flex items-start gap-3 p-3.5 rounded-2xl border ${style.border} ${style.bg}`}>
              <div className={`flex-shrink-0 flex items-center justify-center h-7 w-7 rounded-lg bg-slate-900/60 border ${style.border}`}>
                <Icon className={`h-3.5 w-3.5 ${style.icon}`} />
              </div>
              <p className="text-xs text-slate-300 leading-relaxed font-medium flex-1">{typeof rec === 'string' ? rec : rec.text || JSON.stringify(rec)}</p>
            </div>
          );
        })}
      </div>
      <p className="text-[9px] text-slate-600 text-center mt-4">Generated by Gemini AI · Personalized for your exam readiness profile</p>
    </div>
  );
};
export default RecommendationPanel;