import { Sparkles, Lightbulb, AlertCircle, TrendingUp } from 'lucide-react';
const ICONS = [Lightbulb, AlertCircle, TrendingUp, Sparkles];
const GRADIENTS = [
  { border: 'border-indigo-500/20', bg: 'bg-indigo-500/6', icon: 'text-indigo-400', badge: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/20' },
  { border: 'border-amber-500/20',  bg: 'bg-amber-500/6',  icon: 'text-amber-400',  badge: 'bg-amber-500/15 text-amber-300 border-amber-500/20' },
  { border: 'border-cyan-500/20',   bg: 'bg-cyan-500/6',   icon: 'text-cyan-400',   badge: 'bg-cyan-500/15 text-cyan-300 border-cyan-500/20' },
  { border: 'border-violet-500/20', bg: 'bg-violet-500/6', icon: 'text-violet-400', badge: 'bg-violet-500/15 text-violet-300 border-violet-500/20' },
  { border: 'border-rose-500/20',   bg: 'bg-rose-500/6',   icon: 'text-rose-400',   badge: 'bg-rose-500/15 text-rose-300 border-rose-500/20' },
];
const RevisionRecommendationCard = ({ recommendations = [], updatedAt, onRecalculate, loading }) => {
  if (!recommendations.length) {
    return (
      <div className="bg-slate-900/40 border border-slate-800/70 rounded-3xl p-6 backdrop-blur-md flex flex-col items-center justify-center min-h-[180px] text-center">
        <Sparkles className="h-8 w-8 text-slate-600 mb-3" />
        <p className="text-sm text-slate-500 font-medium">No AI tips yet</p>
        <p className="text-xs text-slate-600 mt-1 mb-4">Click Recalculate to generate personalized advice</p>
        {onRecalculate && (
          <button
            onClick={onRecalculate}
            disabled={loading}
            className="px-4 py-2 rounded-xl bg-indigo-500/20 border border-indigo-500/20 text-indigo-300 text-xs font-bold hover:bg-indigo-500/30 transition-all cursor-pointer disabled:opacity-50"
          >
            {loading ? 'Generating...' : '✨ Generate AI Tips'}
          </button>
        )}
      </div>
    );
  }
  return (
    <div className="bg-slate-900/40 border border-slate-800/70 rounded-3xl p-6 backdrop-blur-md shadow-xs">
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary animate-pulse" />
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">AI Revision Tips</h3>
        </div>
        {updatedAt && (
          <span className="text-[9px] text-slate-600 font-medium hidden sm:block">Updated {updatedAt}</span>
        )}
      </div>
      <div className="space-y-2.5">
        {recommendations.map((rec, idx) => {
          const Icon = ICONS[idx % ICONS.length];
          const style = GRADIENTS[idx % GRADIENTS.length];
          return (
            <div
              key={idx}
              className={`flex items-start gap-3 p-3.5 rounded-2xl border transition-all duration-200 ${style.border} ${style.bg}`}
            >
              <div className={`flex-shrink-0 flex items-center justify-center h-7 w-7 rounded-lg bg-slate-900/60 border ${style.border}`}>
                <Icon className={`h-3.5 w-3.5 ${style.icon}`} />
              </div>
              <p className="text-xs text-slate-300 leading-relaxed font-medium flex-1">
                {typeof rec === 'string' ? rec : rec.text || JSON.stringify(rec)}
              </p>
            </div>
          );
        })}
      </div>
      <p className="text-[9px] text-slate-600 text-center mt-4 font-medium">
        Generated by Gemini AI · Based on your Ebbinghaus retention data
      </p>
    </div>
  );
};
export default RevisionRecommendationCard;